name: Run scheduled action
on: workflow_dispatch
  
jobs:
  chlgamescorebot-post:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: actions/cache@v2
        with:
          path: ~/Documents/CHLGameScore/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install packages
        run: Rscript -e 'install.packages(c("rvest", "xml2", "glue", "jsonlite", "tidyr", "dplyr", "gt", "webshot", "twitteR"), dependencies = TRUE); webshot::install_phantomjs()'
      - name: Generate and post tweet
        run: Rscript script.R
