name: Run scheduled action
on: 
  schedule:
    - cron: '0 19 * * *'

jobs:
  chlgamescorebot-post:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: Rscript -e 'install.packages(c("rvest", "xml2", "glue", "jsonlite", "tidyr", "dplyr", "gt", "webshot", "twitteR"), dependencies = TRUE); webshot::install_phantomjs()'
      - name: Generate and post tweet
        run: Rscript script.R
