name: Run scheduled action
on:
  schedule:
    # You need to set your schedule here
    - cron: "0 5 * * *"

jobs:
  pull_data:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      # If using R:
      - name: Set up R 4.0.3
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.0.3"

      - name: Install dependencies
        run: |
          install.packages(c('rvest', 'xml2', 'glue', 'jsonlite', 'tidyr', 'dplyr', 'gt', 'webshot'))
        shell: Rscript {0}

      # If using R:
      - name: Pull data
        run: Rscript --vanilla script.R
