name: Run scheduled action
on:
  schedule:
    # You need to set your schedule here
    - cron: "0 5 * * *"

jobs:
  pull_data:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      # If using R:
      - name: Set up R 4.0.3
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.0.3"

      # If using R:
      - name: Install dependencies
        run: Rscript --vanilla install.R

      # If using R:
      - name: Pull data
        run: Rscript scripttorun.R
